# Generated by Django 5.2 on 2025-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delta',
            fields=[
                ('model_number', models.CharField(primary_key=True, serialize=False)),
                ('material_type', models.CharField()),
                ('collection', models.CharField(blank=True, null=True)),
                ('description', models.CharField()),
                ('finish', models.CharField()),
                ('list_price', models.FloatField()),
                ('product_image', models.URLField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moen',
            fields=[
                ('model_number', models.CharField(primary_key=True, serialize=False)),
                ('material_type', models.CharField()),
                ('collection', models.CharField(blank=True, null=True)),
                ('description', models.CharField()),
                ('finish', models.CharField()),
                ('list_price', models.FloatField()),
                ('product_image', models.URLField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
