# Generated by Django 5.2 on 2025-04-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delta_moen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delta',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delta',
            name='finish',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delta',
            name='list_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delta',
            name='material_type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moen',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moen',
            name='finish',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moen',
            name='list_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moen',
            name='material_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
