# Generated by Django 5.2 on 2025-04-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_misc_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='builder',
            old_name='base_lav_faucet',
            new_name='base_pri_lav_faucet',
        ),
        migrations.AddField(
            model_name='builder',
            name='base_sec_lav_faucet',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delta',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delta',
            name='product_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moen',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moen',
            name='product_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
